version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: devdb
    networks:
      - main
  # dev-elastic-search:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:8.8.1
  #   ports:
  #     - 9200:9200
  #   environment:
  #     - discovery.type=single-node
  #     - xpack.security.enabled=false
  #   networks:
  #     - main
networks:
  main:
