version: '3.8'
services:
  test-db:
    image: postgres:13
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: testdb
    networks:
      - main
  # test-elastic-search:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:8.8.1
  #   ports:
  #     - 9201:9200
  #   environment:
  #     - discovery.type=single-node
  #     - xpack.security.enabled=false
  #   networks:
  #     - main
networks:
  main:
